### PR TITLE
Added DSC JSS

### PR DESCRIPTION
**Pull request by PragatiVerma18**
Added DSC JSS to the map

```JavaScript
{
    longitude: 77.391029,
    latitude: 28.535517,
    batch: 2020,
    photo: PragatiVerma,
    region: "Asia",
    skills: ["App Dev", "Web Dev", "Cloud"],
    name: "Pragati Verma",
    bio: "May the code be with you!",
    url: "https://dsc.community.dev/jss-academy-of-technical-education-noida/",
    chapterName: "JSS Academy of Technical Education, Noida",
    github: "https://github.com/PragatiVerma18",
    linkedin: "https://www.linkedin.com/in/pragativerma18/",
    twitter: "https://twitter.com/pragati_verma18",
    portfolio: "http://pragativerma18.github.io/Resume",
}
```

### CODE REVIEW

**Review by abhinavsri360 — APPROVED** [review]
I see a lot of json chnging just due to indentation changes, I will add your object manually, just to be sure of not losing anyone on the map.

**Comment by abhinavsri360** [comment]
Moreover, the file size seems to be pretty huge, can you send a jpg of a file with less size?

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
@PragatiVerma18 Looks good to me except for the PNG and indentation changes. Should have been JPG. The formatting changes are valid though.

@abhinavsri360 View changes ignoring whitespace [here](https://github.com/abhinavsri360/GDSC-Lead-Map/pull/69/files?diff=split&w=1).

**Comment by abhinavsri360** [comment]
I never clicked that settings icon ;-;
Thanks, I am discovering a new feature every day. 🥺

**Comment by PragatiVerma18** [comment]
> @PragatiVerma18
> Moreover, the file size seems to be pretty huge, can you send a jpg of a file with less size?

Here's the image, should I add it to code, or will you be doing that?
PragatiVerma

**Comment by abhinavsri360** [comment]
I think you can push the changes straight away, now that I know how to split view 😓

**Comment by PragatiVerma18** [comment]
> I think you can push the changes straight away, now that I know how to split view 😓

Hey @abhinavsri360, I have updated the image. Do let me know if any other change is required.

**Review by abhinavsri360 — APPROVED** [review]
Yeah, Looks good to me.
Thanks for adding yourself!

**Pull request merged**
