### PR TITLE
Added DSC VIT Bhopal

### PR DESCRIPTION
**Pull request by abhishek2x**
Added DSC VIT Bhopal

### CODE REVIEW

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
@abhishek2x Please submit a clean PR with only the map data. Follow the steps mentioned in the [contributing guidelines](https://github.com/abhinavsri360/GDSC-Lead-Map/blob/main/CONTRIBUTING.md).

**Comment by abhishek2x** [comment]
Added DSC VIT Bhopal

**Comment by aravindvnair99** [comment]
> Added DSC VIT Bhopal

@abhishek2x You modified the dependency files as well in addition to that. Please submit a clean PR with only the map data. Follow the steps mentioned in the [contributing guidelines](https://github.com/abhinavsri360/GDSC-Lead-Map/blob/main/CONTRIBUTING.md).

**Review by abhinavsri360 — CHANGES_REQUESTED** [review]
Hey @abhishek2x 
You can remove the following files as part of the PR i.e., `package-lock.json` and `yarnlock`

**Comment by abhishek2x** [comment]
Noted, will create an updated PR.

**Comment by abhinavsri360** [comment]
> > Added DSC VIT Bhopal
> 
> @abhishek2x You modified the dependency files as well in addition to that. Please submit a clean PR with only the map data. Follow the steps mentioned in the [contributing guidelines](https://github.com/abhinavsri360/GDSC-Lead-Map/blob/main/CONTRIBUTING.md).

Hey,
I was thinking if we should add these files in gitignore or not, because dependency changes often happen because of the machine a dev is using.

**Comment by aravindvnair99** [comment]
> Hey @aravindvnair99,
> I was thinking if we should add these files in gitignore or not, because dependency changes often happen because of the machine a dev is using.

@abhinavsri360 Ah nope, that would be a bad idea. The reason the lock files are changing is because they are doing `npm install` or `yarn install`. But we need to retain the lock files so that the wrong dependency or incompatible dependency doesn't get deployed.

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
Hey @abhishek2x!

Please don't delete the file. That would delete it from the repo itself. Instead you have 2 options:

1. Make new PR following the guidelines.
2. Revert the commit and force push to overwrite your PR.

**Comment by abhinavsri360** [comment]
> > Hey @aravindvnair99,
> > I was thinking if we should add these files in gitignore or not, because dependency changes often happen because of the machine a dev is using.
> 
> @abhinavsri360 Ah nope, that would be a bad idea. The reason the lock files are changing is because they are doing `npm install` or `yarn install`. But we need to retain the lock files so that the wrong dependency or incompatible dependency doesn't get deployed.

Yep cool!

**Review by aravindvnair99 — APPROVED** [review]

**Review by abhinavsri360 — APPROVED** [review]
LGTM!

**Pull request merged**
