### PR TITLE
Leads count block added

### PR DESCRIPTION
**Pull request by soyo-kaze**
## Added Leads count block
* It shows how many leads have added themselves to the platform.
* Gets the length of the json file which stores all the data that's it. 
* Also I use prettier extension so it formats the code and make it more readable by auto indentation on saves. That's why it show whole file as green :P 

> wanted to push this with a bigger contribution 😅  but it'll take time to work that thing up 😄 . Next PR would be more useful :P

### CODE REVIEW

**Review by abhinavsri360 — CHANGES_REQUESTED** [review]
@soyo-kaze 
Could you not push `package-lock.json` in the PR and can you pull the changes and refactor this? because there are merge conflicts.

**Comment by soyo-kaze** [comment]
oh ok wil do

**Comment by abhinavsri360** [comment]
btw simply removing `package-lock.json` from the PR would do the job, I mean exclude it from the PR.

**Comment by soyo-kaze** [comment]
How About now @abhinavsri360 ?

**Comment by abhinavsri360** [comment]
No conflicts, let's wait for the build 😄

**Comment by soyo-kaze** [comment]
> btw simply removing `package-lock.json` from the PR would do the job, I mean exclude it from the PR.

oh didn't knew that before 😅. Will keep that in mind next time 👍

**Review by abhinavsri360 — COMMENTED** [review]
Thanks for the feature update!

**Pull request merged**
