### PR TITLE
added shreyasmalewar

### PR DESCRIPTION
**Pull request by shreyasmalewar**

### CODE REVIEW

**Comment by abhinavsri360** [comment]
Hey @shreyasmalewar seems like you changed package.json, and package-lock.json.
As per the Readme, you were supposed to add details in the PR body.
There are 2 things that can be done now:
1) You create a new PR, with no other changes than the typo fix and image upload
2) I do that for you.

What do you prefer? ;)

**Comment by shreyasmalewar** [comment]
> Hey @shreyasmalewar seems like you changed package.json, and package-lock.json.
> As per the Readme, you were supposed to add details in the PR body.
> There are 2 things that can be done now:
> 
> 1. You create a new PR, with no other changes than the typo fix and image upload
> 2. I do that for you.
> 
> What do you prefer? ;)

Hey @abhinavsri360 I'll go with option 1. Will do the needful by tomorrow morning.

**Comment by abhinavsri360** [comment]
> > Hey @shreyasmalewar seems like you changed package.json, and package-lock.json.
> > As per the Readme, you were supposed to add details in the PR body.
> > There are 2 things that can be done now:
> > 
> > 1. You create a new PR, with no other changes than the typo fix and image upload
> > 2. I do that for you.
> > 
> > What do you prefer? ;)
> 
> Hey @abhinavsri360 I'll go with option 1. Will do the needful by tomorrow morning.

Thank you so much!
Have coffee before creating a PR ☕

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
@shreyasmalewar Make sure to sync your fork as well before making changes.

**Comment by shreyasmalewar** [comment]
> @shreyasmalewar Make sure to sync your fork as well before making changes.

Hey, @aravindvnair99 I updated my fork but it resulted in endless merge conflicts. Could you or @abhinavsri360 kindly add my details?

**Comment by aravindvnair99** [comment]
> > @shreyasmalewar Make sure to sync your fork as well before making changes.
> 
> Hey, @aravindvnair99 I updated my fork but it resulted in endless merge conflicts. Could you or @abhinavsri360 kindly add my details?

@shreyasmalewar Ah you should make a new branch and pull into it as you made changes in your main branch itself. Ideally one must make changes in another branch and not the tracking branch. But yeah no problem, I'll send a replacement PR.

**Comment by abhinavsri360** [comment]
I would suggest stashing the changes you made, pull everything and then place a PR again.

**Pull request closed without merging**
