### PR TITLE
Added Aitik(DSC VSSUT)

### PR DESCRIPTION
**Pull request by i-tick**
{
		longitude: 83.90430, 
		latitude: 21.49849,
		batch: 2020,
		photo: aitik,
		region: "Asia",
		skills: ["AI/ML", "Web Dev", "App Dev"],
		name: "Aitik Dandapat",
		bio: "Respect Existance or Expect Resistance",
		url:
			"https://dsc.community.dev/veer-surendra-sai-university-of-technology/",
		chapterName: "Veer Surendra Sai University of Technology, Burla",
		github: "https://github.com/i-tick",
		linkedin: "https://www.linkedin.com/in/aitik-dandapat-b03395184",
		twitter: "https://twitter.com/AitikDandapat"
	}

### CODE REVIEW

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
@i-tick Please follow the [guidelines](https://github.com/abhinavsri360/GDSC-Lead-Map/blob/main/CONTRIBUTING.md). You are not supposed to modify dependency files. Your picture is missing as well.

**Comment by abhinavsri360** [comment]
> @i-tick Please follow the [guidelines](https://github.com/abhinavsri360/GDSC-Lead-Map/blob/main/CONTRIBUTING.md). You are not supposed to modify dependency files. Your picture is missing as well.

+1 on this @i-tick please go through the same.

**Comment by abhinavsri360** [comment]
@i-tick 
Can we have an update on this?

**Comment by aravindvnair99** [comment]
@abhinavsri360 I guess it's better to add manually as @i-tick hasn't responded yet.

**Comment by abhinavsri360** [comment]
Yeah, I'll do that

**Comment by abhinavsri360** [comment]
Hey, but his picture is missing, I don't want to offend anyone :p

**Comment by aravindvnair99** [comment]
> Hey, but his picture is missing, I don't want to offend anyone :p

@abhinavsri360, maybe use his GitHub profile picture: https://avatars.githubusercontent.com/u/46849982

**Comment by abhinavsri360** [comment]
I can, alright, I will :p

**Comment by aravindvnair99** [comment]
@i-tick Reminder

**Pull request closed without merging**
