### PR TITLE
Update PULL_REQUEST.md

### PR DESCRIPTION
**Pull request by todcru**

### CODE REVIEW

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
@todcru You've edited the wrong file. Please follow the instructions mentioned in the README. You should add your data in `/src/components/json/worldData.js`.

**Comment by todcru** [comment]
Oh my bad... I'll change

**Comment by aravindvnair99** [comment]
> Oh my bad... I'll change

@todcru Close this PR and send a new one as you modified the wrong file.

**Comment by todcru** [comment]
> > Oh my bad... I'll change
> 
> @todcru Close this PR and send a new one as you modified the wrong file.

can you check now bro

**Comment by aravindvnair99** [comment]
> > > Oh my bad... I'll change
> > 
> > 
> > @todcru Close this PR and send a new one as you modified the wrong file.
> 
> can you check now bro

@todcru You didn't close this PR and send new PR.

**Pull request closed without merging**
