### PR TITLE
Added my details

### PR DESCRIPTION
**Pull request by mriceflame**
Fixes #

## Proposed Changes

-
-
-

### CODE REVIEW

**Comment by mriceflame** [comment]
I have tested it on local host, everything if fine feel free to merge the PR.

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
@mriceflame Please revert your changes to the dependency lock file.

**Comment by mriceflame** [comment]
I have not changes anything in package-lock.json
its might be due to LF will be replaced by CRLF in package-lock.json.
which is because i am using windows to push the code and it was first uploaded from a unix.n Unix systems the end of a line is represented with a line feed (LF). In windows a line is represented with a carriage return (CR) and a line feed (LF) thus (CRLF). when you get code from git that was uploaded from a unix system they will only have an LF.

**Comment by abhinavsri360** [comment]
@mriceflame 
That is fine, could you remove that file from the PR itself?
Just so no changes are made to the same.

**Comment by mriceflame** [comment]
Ok i will.

**Comment by aravindvnair99** [comment]
> I have not changes anything in package-lock.json
> its might be due to LF will be replaced by CRLF in package-lock.json.
> which is because i am using windows to push the code and it was first uploaded from a unix.n Unix systems the end of a line is represented with a line feed (LF). In windows a line is represented with a carriage return (CR) and a line feed (LF) thus (CRLF). when you get code from git that was uploaded from a unix system they will only have an LF.

@mriceflame No, it's not that. Git is smart enough to convert line/file ending automatically.

The real reason is that you are using `npm` version `6`, while the lock file in the `main` branch was made using version `7`. When you installed the module, you downgraded the lock file from version `2` to version `1`. `npm` version `6` and below uses version 1 lock file and `npm` version `7` and above use version `2` lock file. Hence, as I mentioned, please revert your changes to the lock file so that @abhinavsri360 can merge your changes.

Your changes:

https://github.com/abhinavsri360/GDSC-Lead-Map/blob/442f1701a2d4c0489bd5738ccfeebfb681a49a69/package-lock.json#L4

Original file:

https://github.com/abhinavsri360/GDSC-Lead-Map/blob/dec02ea2f613320af15acfe7ca3a39011fc199a2/package-lock.json#L4

**Comment by mriceflame** [comment]
Thanks, I'll take a look.

**Comment by mriceflame** [comment]
I have deleted the file in my PR will it work this way?

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
@mriceflame Hey! Please don't delete the file. When we merge, it would delete from our repository as well. Undo your changes and commit and push only the two files that are necessary. Refer to the instructions. If you're not familiar with Git to undo commit and force push, you can send a new PR instead. Let us know if you need any help.

**Comment by mriceflame** [comment]
Ok, i have downloaded your package-lock.json and uploaded to my repo, no changes now, have a look and let me know

**Comment by mriceflame** [comment]
Yep, now it changes only 2 files. i think its good to go now.

**Comment by mriceflame** [comment]
Let me know if this will work now. or else i can create a new PR with manually changing that 2 files only.

**Review by aravindvnair99 — APPROVED** [review]
@mriceflame LGTM

@abhinavsri360 Would recommend a squash and merge.

**Review by abhinavsri360 — APPROVED** [review]
LGTM :))

**Pull request merged**
