### PR TITLE
added sanjeev

### PR DESCRIPTION
**Pull request by codersanjeev**
Fixes #

## Proposed Changes

-
-
-

### CODE REVIEW

**Review by aravindvnair99 — APPROVED** [review]

**Review by abhinavsri360 — APPROVED** [review]
Thanks for adding yourself!

**Review by abhinavsri360 — CHANGES_REQUESTED** [review]
Isn't your lead `Monika rajput` ?

**Comment by codersanjeev** [comment]
> Isn't your lead `Monika rajput` ?

Yes, she is for 2020 batch, I'm from 2019 batch.

**Comment by aravindvnair99** [comment]
> Isn't your lead `Monika rajput` ?

@abhinavsri360 He's from 2019.

**Comment by abhinavsri360** [comment]
I did not realise that, 🤦🏻 sorry

**Pull request merged**
