### PR TITLE
Added My Profile details

### PR DESCRIPTION
**Pull request by AkshaySharma008**
Added my details with profile picture. Thanks

### CODE REVIEW

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
@AkshaySharma008 Please follow the [guidelines](https://github.com/abhinavsri360/GDSC-Lead-Map/blob/main/CONTRIBUTING.md). You are not supposed to modify `package-lock.json`

**Comment by AkshaySharma008** [comment]
Hey @aravindvnair99, I perfectly followed the guidelines, I haven't made any changes in Package-lock.json, it might be some indentations check, I am sure I haven't added any external package and all. Please check, I am assuring you that.

**Comment by aravindvnair99** [comment]
> Hey @aravindvnair99, I perfectly followed the guidelines, I haven't made any changes in Package-lock.json, it might be some indentations check, I am sure I haven't added any external package and all. Please check, I am assuring you that.

@AkshaySharma008 No, they aren't indentation changes. You have made 36 additions, 20,991 deletions to that file as visible here: https://github.com/abhinavsri360/GDSC-Lead-Map/pull/73/files#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519

I'm assuming you did `npm install` or `yarn install` and thus the file got modified and you probably didn't notice that file while committing. You have 3 choices:

1. Revert the commit and undo changes to that file alone. Then force push to update this PR.
2. Close this PR, delete your fork (as you modified in your main branch) and redo.
3. Make an empty branch (don't base it out of your main branch as you modified it), pull from this repo, make changes and then make PR.

2nd option would be easiest for you if you aren't familiar with Git.

**Comment by AkshaySharma008** [comment]
Ya, I figured it out. Sending you PR in few minutes. Thanks

**Pull request closed without merging**
