### PR TITLE
Adding Abhinav T B

### PR DESCRIPTION
**Pull request by abhinav-TB**
Fixes #

## Proposed Changes

-
-
-

### CODE REVIEW

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
Hey @abhinav-TB!

Please submit a clean PR with only the map data. Follow the steps mentioned in the [contributing guidelines](https://github.com/abhinavsri360/GDSC-Lead-Map/blob/main/CONTRIBUTING.md).

**Comment by abhinav-TB** [comment]
@abhinavsri360 I have added things according to the guidelines, what are the things i should add or remove

**Review by abhinavsri360 — CHANGES_REQUESTED** [review]
>Hey @abhinav-TB!
Please submit a clean PR with only the map data. Follow the steps mentioned in the contributing guidelines.

+1 to Aravind on this

**Comment by abhinavsri360** [comment]
@abhinav-TB 
Do not include `package-lock.json` and `one.jpg` in the PR.

**Comment by abhinavsri360** [comment]
@abhinav-TB 
The changed file tab still shows 4 files. Please look into it.

**Comment by abhinav-TB** [comment]
@abhinavsri360  the other files are just duplicate images that I deleted

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
@abhinav-TB You aren't supposed to delete the dependency lock file. Please submit a clean PR with only the map data. Follow the steps mentioned in the [contributing guidelines](https://github.com/abhinavsri360/GDSC-Lead-Map/blob/main/CONTRIBUTING.md).

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
@abhinav-TB This is still an invalid PR. Please submit a clean PR with only the map data. Follow the steps mentioned in the [contributing guidelines](https://github.com/abhinavsri360/GDSC-Lead-Map/blob/main/CONTRIBUTING.md).

You have 2 choices:

1. Undo commits, make the right changes and force push to overwrite your PR.
2. Close this PR and send a proper PR.

**Comment by abhinav-TB** [comment]
deleting this one a creating a fresh pr

**Pull request closed without merging**
