### PR TITLE
added profile

### PR DESCRIPTION
**Pull request by zainul1996**
Fixes #

## Proposed Changes

- Include Instagram link too

### CODE REVIEW

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
@zainul1996 Please don't change the dependency files. Follow the guidelines provided. You can either update this PR if you're familiar with Git concepts or you can close this and send a fresh PR with proper changes.

**Comment by zainul1996** [comment]
> @zainul1996 Please don't change the dependency files. Follow the guidelines provided. You can either update this PR if you're familiar with Git concepts or you can close this and send a fresh PR with proper changes.

hey I didn't change any of the dependencies. It probably got auto formatted

**Comment by aravindvnair99** [comment]
> hey I didn't change any of the dependencies. It probably got auto formatted

@zainul1996 It changed when you installed the modules with npm or yarn, whichever it is that you're using. You shouldn't be doing that. You can update your PR for the same.

**Comment by zainul1996** [comment]
I rolledback and pushed only src changes

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
@zainul1996 You have used skills that are not permitted either. Please update them with the ones allowed. Refer to the guidelines for the same.

**Comment by zainul1996** [comment]
I'm sorry for the inconveniences caused, ive updated it again :)

**Review by abhinavsri360 — APPROVED** [review]
Looks good to me, thanks @zainul1996 for adding yourself.
Thanks @aravindvnair99 for reviewing :)

**Pull request merged**
